server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
         
         - id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/api/users/**
         - id: resume-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/api/resumes/**
         - id: tracker-service
           uri: lb://APPLICATION-TRACKER-SERVICE
           predicates:
             - Path=/api/applications/**
         - id: match-service
           uri: lb://MATCH-SERVICE
           predicates:
             - Path=/api/match/**
         - id: interview-prep-service
           uri: lb://INTERVIEW-PREP-SERVICE
           predicates:
              - Path=/api/interview-prep/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
